name: Blazor WASM CI/CD

on:
  push:
    branches: 
      - "main"
      - "dev"

jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Run a diagnostic test
      run: echo "The pipeline triggered successfully"